---
  - name: Check required packages are installed
    yum:
      name: openstack-neutron-lbaas
      state: present

  - name: Copy Avi LBaaS driver files
    copy:
      src: "{{ avi_driver_package_dir|mandatory }}/{{ avi_lbplugin_dir }}"
      dest: "{{ neutron_lbplugin_dir }}"

  - name: Make temporary directory
    tempfile:
      suffix: avi
      state: directory
    register: tempdir

  - name: Copy Avi SELinux policy files
    copy:
      src: "{{ avi_driver_package_dir|mandatory }}/setup/avi_lbaas.{{ item }}"
      dest: "{{ tempdir.path|default('/tmp') }}"
    with_items:
      - pp
      - te

  - name: Avi SELinux policy
    block:
      - name: Install precompiled SELinux policy
        command: "semodule -i {{ tempdir.path|default('/tmp') }}/avi_lbaas.pp"

    rescue:
      - name: Install checkpolicy to recompile SELinux policy
        yum:
          name: checkpolicy
          state: present

      - name: Recompile SELinux policy
        command: "{{ item }}"
        with_items:
          - "checkmodule -M -m -o {{ tempdir.path|default('/tmp') }}/avi_lbaas.mod {{ tempdir.path|default('/tmp') }}/avi_lbaas.te"
          - "semodule_package -o {{ tempdir.path|default('/tmp') }}/avi_lbaas.pp -m {{ tempdir.path|default('/tmp') }}/avi_lbaas.mod"

      - name: Install SELinux policy
        command: "semodule -i {{ tempdir.path|default('/tmp') }}/avi_lbaas.pp"

  - name: Install LBaaSv2 plugin
    include_tasks: neutron_plugin.yml
    vars:
      neutron_additional_plugin: "lbaasv2"

  # Neutron LBaaSV2 lets you specify more than one service_provider, so we use
  # this instead of ini_file
  - name: Configure Neutron LBaaS
    lineinfile:
      path: /etc/neutron/neutron_lbaas.conf
      insertafter: '\[service_providers\]'
      line: "service_provider=LOADBALANCERV2:avi:neutron_lbaas.drivers.avi.avi_driver.AviDriver:default"
      backup: yes
      group: neutron
      mode: 0640
    notify: restart neutron

  # https://github.com/ansible/ansible/issues/29688 diff mode does not respect
  # no_log
  - name: Configure Avi LBaaS Driver
    ini_file:
      path: /etc/neutron/neutron_lbaas.conf
      section: avi_adc
      option: "{{ item.option }}"
      value: "{{ item.value }}"
      backup: yes
      group: neutron
      mode: 0640
    notify: restart neutron
    no_log: "{{ item.no_log|default(false) }}"
    with_items:
      - { option: "address", value: "{{ avi_controller_ip|mandatory }}" }
      - { option: "user", value: "{{ avi_controller_admin_user }}" }
      - { option: "password", value: "{{ avi_controller_admin_password|mandatory }}", no_log: true }
      - { option: "cloud", value: "{{ avi_controller_cloud }}" }
