---
  - name: restart neutron
    systemd:
      name: neutron-*
      state: restarted

  - name: restart heat
    systemd:
      name: openstack-heat-*
      state: restarted

# Order of handler exectution is the order they are defined here, not the order they are notified on
# a task. The rebuild cache step must happen before restarting httpd
# https://docs.openstack.org/neutron-lbaas-dashboard/pike/installation.html
  - name: rebuild cache
    command: "/usr/share/openstack-dashboard/manage.py {{ item }}"
    with_items:
      - "collectstatic --noinput"
      - "compress --force"

  - name: restart httpd
    systemd:
      name: httpd
      state: restarted
