---
  - name: restart neutron
    systemd:
      name: neutron-*
      state: restarted

  - name: restart heat
    systemd:
      name: openstack-heat-*
      state: restarted

  - name: restart httpd
    systemd:
      name: httpd
      state: restarted
