---
  - name: restart neutron
    systemd:
      name: neutron-*
      state: restarted

  - name: restart heat
    systemd:
      name: openstack-heat-*
      state: restarted

  - name: rebuild cache
    # Must come before restart httpd
    command: "/usr/share/openstack-dashboard/manage.py {{ item }}"
    with_items:
      - "collectstatic --noinput"
      - "compress --force"

  - name: restart httpd
    systemd:
      name: httpd
      state: restarted
